version: '3'
services:
    node:
        container_name: node
        build:
            context: .
        tty: true
        volumes: 
            - ./app:/node/app
        ports:
            - "8080:8080"